[build-system]
requires = ["setuptools", "wheel", "Cython ~= 3.0.0a11", "numpy"]
build-backend = "setuptools.build_meta"

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
strict = true
packages = "pyprotolinc"
